# Generated by Django 4.2.14 on 2024-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(default='Default name', max_length=200),
            preserve_default=False,
        ),
    ]
